import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../components/website/Navbar";
import { Footer } from "../components/website/Footer";
import { MiniNav } from "../components/website/MiniNav";
import { DarkModeProvider } from "../components/darkmode/DarkModeProvider";
import { Roboto, Merriweather } from 'next/font/google';

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// Merriweather Fonts
 const merriweather = Merriweather({
  weight: ['300', '400', '700'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--merriweather',
});

// Roboto Fonts
 const roboto = Roboto({
  weight: ['300', '400', '500', '700'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--roboto',
});
export const metadata: Metadata = {
  title: "Rob J Solution",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      > */}
    {/* <body 
    // className=" text-secondary scroll-smooth" 
    > */}
    <body
     className={`${roboto.variable} ${merriweather.variable} text-secondary scroll-smooth`}
                >
      <DarkModeProvider/>
        <MiniNav/>
        <Navbar/>
        {children}
        <Footer/>
        
      </body>
    </html>
  );
}
